### ISSUE TITLE
Window controls color should be changed as well (unity)

### ISSUE THREAD

**Issue by vitalykorolev** [actionless/oomox#26] opened 2016-05-03 17:41 UTC
It seems that oomox doesn't change colors of window controls, but I can easily do it with

grep -ril '#f0544c' | xargs sudo  sed -i 's/#[f|F]0544[c|C]/#3465a4/g'

so it should be possible to add.

To clarify, by window controls I mean close, minimize, and maximize buttons that seem to stay red in custom themes that oomox exports.

**Comment by actionless** [comment] 2016-05-04 11:03
do you want to prepare a PR? i don't really want tinkering with a VM in order to test it

**Comment by vitalykorolev** [comment] 2016-05-04 16:20
:) I can give it a shot.

**Comment by Sadi58** [comment] 2016-10-25 22:53
Interesting, when started with command `sudo nautilus`, we see a Gnome-style window of Nautilus with **window control buttons in oomox-specified color** (no titlebar, and no menubar - visible or invisible ;-)

**Comment by actionless** [comment] 2016-10-26 00:22
@Sadi58  could you explain how that's related to the theme itself?

**Comment by Sadi58** [comment] 2016-10-26 08:56
This interesting situation is a combination of Ubuntu and theming issues I think.

It seems the new Gnome window theming (with headerbar instead of titlebar) uses colors from the GTK theme in window control buttons - so I see them changing to blue when hovering, etc.

At first I had manually changed the color codes in prelight and pressed svg images to Mac-style red, amber and green, but after seeing this behavior in root mode I should better make all of them blue for the sake of consistency.

As a final note: I think the replacement color (#3465a4) suggested above should better be changed to that (lighter) shade of blue used for hover/selection also for the sake of consistency.

**Comment by actionless** [comment] 2016-10-26 11:53
I am not using ubuntu/unity on my own so i can only accept a PR from a person who is doing that and have fixed it.

If you are going up for this, please keep in mind what in the theme template for unity (https://github.com/actionless/oomox/tree/master/src/unity) you have to replace it to a variable, not hardcoded color, see the example of how theme variables are used instead of hardcoded colors:
https://github.com/actionless/oomox/blob/master/src/gtk-3.20/scss/_global.scss#L6-L17

**Comment by Sadi58** [comment] 2016-10-26 15:28
The problem is this enhancement proposal suggests editing svg images in the unity subdirectory while the point you're making concerns css coding AFAIK.
I have only beginner-level skills in this field, and I guess you need to incorporate a sort of module that will  replace the default value `[f|F]0544[c|C]` with the user-defined **selected_bg_color** which would be the variable `%SEL_BG%`
I've manually done it with this command `sed -i "s/#[F|f]0544[C|c]/#42a5f5/g" "close_focused_prelight.svg" "close_focused_pressed.svg" "maximize_focused_prelight.svg" "maximize_focused_pressed.svg" "minimize_focused_prelight.svg" "minimize_focused_pressed.svg" "progress_bar_fill.svg" "unmaximize_focused_prelight.svg" "unmaximize_focused_pressed.svg"`

**Comment by actionless** [comment] 2016-10-26 15:53
try `sed -i "s/#[F|f]0544[C|c]/#%SEL_BG%/g" `, generate theme and see if the color is dynamic now

**Comment by Sadi58** [comment] 2016-10-26 17:35
Sorry, I don't know how and where to generate theme manually in this way.
I could only run the sed command above in the unity folder created by oomox, and it worked. But I think there should be a Python command to be incorporated in one of your scripts to include this feature as well. I know just a little bit Bash but no Python unfortunately.

**Comment by actionless** [comment] 2016-10-31 16:57
you have to change only svg files' templates in `./src` directory, no need to do any changes in application code

**Comment by actionless** [comment] 2017-03-05 13:27
seems to be closed in version 1.2

**Closed by actionless** 2017-03-05 13:27 UTC
Labels: enhancement, PRs welcome
