### ISSUE TITLE
White pixels in the corners of Nautilus

### ISSUE THREAD

**Issue by Sadi58** [actionless/oomox#49] opened 2016-10-25 22:45 UTC
First of all, thanks a lot for this great utility!
I see some differences between the upstream **Numix** theme and the one customized by **oomox** - other than the colors modified.

For example:

1) There two _tiny white dots at the right and left bottom corners of the titlebar in some apps_ like nautilus and gedit. I suspect this is a result of round top corners of Gnome-style window that doesn't have a titlebar as displayed when those apps are started with commands `sudo nautilus` and `sudo gedit`. _I suspect this might be a Unity specific issue._

2) Different _tab styling_ :  in the active tab, oomox displays a colored top line only while Numix has a colored title and a colored bottom line, etc.

**Comment by actionless** [comment] 2016-10-26 00:24
1) confirming this one as a bug
2) that's by design, feel free to submit PR implementing optional tab appearance

**Comment by Sadi58** [comment] 2016-10-26 09:12
2) If that's by design, no problem. Actually, on second thought, I like your choice better ;-)

1) I see those white dots at the top right and left corners of the toolbar (and immediately below the titlebar) every time I start nautilus and gedit. And this doesn't occur in Numix.

**Comment by Sadi58** [comment] 2016-10-28 12:05
Correction, I see it in Numix as well, though not always - I couldn't quite figure out but maybe after switching from another theme without such an issue :-\)
It seems this is not an oomox bug after all - it should be solved somehere upstream (Numix or Unity). So as far as I'm concerned you may well close this ;-)

**Comment by actionless** [comment] 2016-10-29 09:31
let's better keep this one open -- if I or someone else will find the root cause of the issue here the fix can be submitted to the Numix upstream anyway

**Comment by Sadi58** [comment] 2016-10-31 07:31
I've just had a closed look at this issue, checking with about a dozen most frequently used apps, and also comparing with Ubuntu's default Ambiance theme:
This only occurs in Nautilus, and Ambiance doesn't have it.
So it's probably a Numix bug.

**Comment by actionless** [comment] 2016-10-31 12:51
so what about your `gtk3` version?

and also could you please check this issue using Openbox or any other WM instead of unity?

**Comment by Sadi58** [comment] 2016-10-31 12:57
Sorry, I forgot that. I'm currently on Ubuntu 16.10, i.e. GTK 3.20, Nautilus 3.20.
I don't have any other WM but I don't think that they would have such a problem which occurs only in Nautilus and gedit versions 3.20, using GTK 3.20.
The latest thing I've noticed is that gedit shows this always with oomox-numix and never with Numix ("always" and "never" in this case are limited to my best judgement of course ;-)

**Comment by megax** [comment] 2016-10-31 13:46
@actionless merge code: https://github.com/numixproject/numix-gtk-theme/commit/a457b8fd5bc04d3778bb676277b55338f3ac652c

**Comment by actionless** [comment] 2016-10-31 16:28
thanks @megax !

merged https://github.com/actionless/oomox/commit/a457b8fd5bc04d3778bb676277b55338f3ac652c

**Closed by actionless** 2016-10-31 16:28 UTC
Labels: bug, need info
